---
- hosts: all
  become: true
  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Descargar Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.41.0/prometheus-2.41.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extraer Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Configurar Prometheus como servicio
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=nobody
          ExecStart=/opt/prometheus-2.41.0.linux-amd64/prometheus --config.file=/opt/prometheus-2.41.0.linux-amd64/prometheus.yml
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Iniciar y habilitar Prometheus
      systemd:
        name: prometheus
        enabled: true
        state: started

    - name: Agregar repositorio de Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana
        update_cache: yes

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Iniciar y habilitar Grafana
      systemd:
        name: grafana-server
        enabled: true
        state: started
